version: '3.8'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  webserver:
    image: nginx:alpine
    depends_on:
      - php-fpm
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${NGINX_HOST_HTTP_PORT:-80}:80"
    networks:
      - backend
      - frontend
    env_file: .env
    restart: unless-stopped

  php-fpm:
    image: php:${PHP_VERSION}-fpm-alpine
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
      - ./.docker/php/${PHP_VERSION}/conf.d:/usr/local/etc/php/conf.d/
    networks:
      - backend
    env_file: .env
    restart: unless-stopped

  mysql:
    image: mariadb:latest
    ports:
      - "3306:3306"
    networks:
      - backend
    env_file: .env
    restart: unless-stopped